### ISSUE TITLE
Getting rid of `action/cache` for `release.yml`

### ISSUE THREAD

**Issue by oscard0m** [probot/octokit-plugin-config#108]
After adding `cache` option to `setup-node`, would have sense to remove this step?

https://github.com/probot/octokit-plugin-config/blob/dd62895693e2f8393ee47f37876d57580260cf13/.github/workflows/release.yml#L17-L22

**Comment by gr2m** [comment]
I say yes. I'd check for a step with a `uses` key that starts with `actions/cache` and `with.path` being set to `~/.npm`

**Comment by wolfy1339** [comment]
Those lines are no longer present. This has been fixed already
