### ISSUE TITLE
Getting rid of `action/cache` for `test.yml`

### ISSUE THREAD

**Issue by oscard0m** [probot/octokit-plugin-config#109]
After adding `cache` option to `setup-node`, would have sense to remove this step?

https://github.com/probot/octokit-plugin-config/blob/dd62895693e2f8393ee47f37876d57580260cf13/.github/workflows/test.yml#L23-L28

**Comment by gr2m** [comment]
same as https://github.com/probot/octokit-plugin-config/issues/108, let's discuss there, no need to open separate issues for separate workflow files as it's a generic CI setup step that can be applied to all
