### ISSUE TITLE
Cannot read property `get` of undefined

### ISSUE THREAD

**Issue by NebelNidas** [probot/octokit-plugin-config#110]
I'm trying to use this plugin like this:
```js
const { Octokit } = require('@octokit/core');


module.exports = async (context) => {

  const { owner, repo } = context.repo();
  const octokit = new Octokit();
  const lookupTable = await octokit.config.get({
    owner,
    repo,
    path: 'lookup-table.yaml',
  });
  
}
```

But I always get the following error: `ERROR event: Cannot read property 'get' of undefined (id=7600d710-dfc5-11eb-8be9-a0fed017660a)  TypeError: Cannot read property 'get' of undefined`

Can you please help me getting my head wrapped around this? Sorry if this is trivial, but I'm quite a JavaScript noobie

**Comment by gr2m** [comment]
I assume the `async (context) => { ... }` function is a Probot event handler function? Use `context.octokit` instead of importing `@octokit/core` and instantiating it. `context.octokit` is a pre-authenticated Octokit instance with all the plugins loaded, including `octokit-plugin-config`
