### ISSUE TITLE
Allow multiple _extends sources

### ISSUE THREAD

**Issue by micimize** [probot/octokit-plugin-config#82]
**What’s missing?**
`_extends` would be even more useful if it accepted a list as a parameter, allowing for partials/mixins.

**Why?**
I need to break protobot/settings configuration in to separate files for my org so that some are optional to repo maintainers while others are mandatory/protected.

**Alternatives you considered**
I could fork protobot/settings and alter it to my needs

**Comment by gr2m** [comment]
sounds like a concern very specific to settings, I think it should be addressed there? This request didn't come up before, so I'm reluctant to implement it and maintain it forever.

How would the API look like?

**Comment by micimize** [comment]
`_extends` could just accept and merge a list:
```yaml
_extends: github-settings, other/github-settings, repo/path/to/config.yaml
```

It isn't even entirely correct to say it's a settings concern. After more thought I'm pretty sure it will be better if I fork the project instead of trying to shoehorn it to my needs anyhow.

I do think this may be useful for larger organizations, but feel free to close it for now.

If I find a compelling case for this in the future, would you accept a PR? I think it could be done rather cleanly but it would take some doing so I certainly understand your reticence.

**Comment by gr2m** [comment]
thanks for understanding! Your approach sounds great, and once you run your own fork and confirm it's usefulness, that will definitely make a valid use case. You can also start a pull request so we have a base of discussion. If it's a very simple change that is easy to test/maintain, it will make it much more likely to add it to `@probot/octokit-plugin-config`
