### ISSUE TITLE
Doesn't actually work with JSON?

### ISSUE THREAD

**Issue by ScottChapman** [probot/octokit-plugin-config#90]
So I wanted to use JSON (since it looks like there is support) for my configuration files, but it doesn't look like there is any attempt to parse the JSON. See
https://github.com/probot/octokit-plugin-config/blob/main/src/util/get-config-file.ts#L72-L77

At this point the data IS the contents of the file, and is a serialized JSON object. It just isn't getting parsed.

Will convert my work to YAML for now, but thought this should get fixed (looks like the test is assuming what gets returned is the JSON, not `raw` which is in the request)

**Comment by Uzlopak** [comment]
It is already parsed to JSON when the content-type header is set to application/json


```ts
  it("_extends: can combine json", async () => {
    const mock = fetchMock
      .sandbox()
      .get(
        "https://api.github.com/repos/org/github-settings/contents/.github%2Fsettings.yml",
        JSON.stringify({
          a: "word"
        })
      )
      .get(
        "https://api.github.com/repos/org/repo-b/contents/.github%2Fsettings.yml",
        JSON.stringify({
          "_extends": "github-settings",
          b: 4
        })
      );

    const octokit = new TestOctokit({
      request: {
        fetch: mock,
      },
    });
    const result = await octokit.config.get({
      owner: "org",
      repo: "repo-b",
      path: ".github/settings.yml",
    });

    expect(result.config).toEqual({
      "a": "word",
      "b": 4,
    });
    expect(result).toMatchSnapshot("result");
    expect(mock.done()).toBe(true);
  });
```
