### ISSUE TITLE
sets incorrect accept header when media type previews are set

### ISSUE THREAD

**Issue by ScottChapman** [probot/octokit-plugin-config#91]
I'm using with @octokit/rest-V18.5.3 I've added the plugin like:
```javascript
const { Octokit } = require('@octokit/rest');
const { config, composeConfigGet } = require("@probot/octokit-plugin-config");

const MyOctokit = Octokit.plugin(config);
```
But when I try to get the config (this works perfectly with Probot) with my own instance of Octokit/rest it finds my YAML file, but the contents are base64 encoded, so the plugin basically thinks the file is actually a directory or a submodule:
https://github.com/probot/octokit-plugin-config/blob/main/src/util/get-config-file.ts#L68

**Comment by gr2m** [comment]
sorry I don't quite get your error description. Could you share a minimal test case to reproduce the problem?

**Comment by ScottChapman** [comment]
yea, I started one earlier. Will post it when I get it completed.

**Comment by ScottChapman** [comment]
OK, I got it reproduced [here](https://github.ibm.com/scottchapman/probot-config-plugin-bug)

It appears to only happen when using any previews. If you comment those out it works fine. Doesn't seem to matter which previews are used. Interesting eh?

I think the fix is to support base64 encoded results. I think there are different ways to determine if results are a directory or submodule

**Comment by gr2m** [comment]
I don't see that repository, can you post it on github.com? I get

<img width="994" alt="image" src="https://user-images.githubusercontent.com/39992/119696903-81b1ec80-be04-11eb-8d0c-56d6b256fba6.png">

**Comment by ScottChapman** [comment]
Sorry, [here](https://github.com/ScottChapman/probot-config-plugin-bug)

**Comment by gr2m** [comment]
Thanks, I was able to reproduce the problem

by the way:

```js
const Public_Octokit = new MyOctokit({
   auth: `token ${process.env.GIT_TOKEN}`,
  previews,
);
```

you can set `auth: process.env.GIT_TOKEN`, no need for the `token ` prefix

**Comment by gr2m** [comment]
This might be a GitHub API bug, I'll check in with them.

Octokit correctly combines the preview with the format to the `Accept` header

```
Accept: application/vnd.github.luke-cage-preview.raw
```

But the API responds with JSON instead of the raw content as it should.

What I would recommend you to do is not to set preview headers globally, but only on the requests where you need them. You can add

```js
  mediaType: {
    previews: ['luke-cage']
  }
```

to the request options to enable the `luke-cage` preview

But I think `luke-cage` is a required preview, which means it gets set for you automatically if you use the APIs that it is required for

**Comment by gr2m** [comment]
I wasn't able to reproduce the problem with curl or fetch, must be a bug with octokit

```js
> await (await fetch("https://api.github.com/repos/ScottChapman/probot-config-plugin-bug/contents/config.yaml", {headers: {accept: "application/vnd.github.luke-cage-preview.raw"}})).text()
< teams:
      CICD Test:
          org: sc-cicd-test
          repoPattern: .*
          securityReviewer: security-reviewers
````

**Comment by ScottChapman** [comment]
Interesting. I can't really work around it exactly (or not easily); there are several previews I am using unfortunately.

**Comment by gr2m** [comment]
no worries, I hope to fix that bug soon. I have a failing test in this PR, now looking into the fix:
https://github.com/probot/octokit-plugin-config/pull/93

**Comment by gr2m** [comment]
can you update to 1.1.0 and check if it resolves your problem?

**Comment by ScottChapman** [comment]
Sure, can do that by the end of the week. Thanks!

**Comment by ScottChapman** [comment]
Works! TY!
